// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpzshwsflglrrezimley.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwenNod3NmbGdscnJlemltbGV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxNjY4MDYsImV4cCI6MjA3OTc0MjgwNn0.dw44N9C8fKJiMAtaMdFpJyF6QsuSaxMaorzSYEwFvtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});